### ISSUE TITLE
How to hide toc in this theme? can't find the options on using hb-blog-post-toc-begin . Thank you.

### ISSUE THREAD

**Issue by creditket** [hbstack/theme-cards#129]
<img width="313" alt="sc" src="https://github.com/hbstack/theme-cards/assets/93809455/926553dd-ed2a-47c8-9b25-d832f61ae46f">

**Comment by razonyang** [comment]
Hmm, there isn't such option. What is your use case?

**Comment by razonyang** [comment]
Btw, you can use `landing` layout with Markdown to write page.

```markdown
---
layout: landing
---

CONTENT HERE
```

**Comment by creditket** [comment]
> Btw, you can use `landing` layout with Markdown to write page.
> 
> ```
> ---
> layout: landing
> ---
> 
> CONTENT HERE
> ```

How can we use landing layout option with this theme?



I am trying to understand this theme first. (since it seems offer a package of features). Most likely just personal blog first.

**Comment by razonyang** [comment]
> ```
> ---
> layout: landing
> ---
> 
> CONTENT HERE
> ```

Specify the `layout` as `landing` on front matter...
