### ISSUE TITLE
Can you please add the option to hide nav-search  on desktop, but show on mobile ?

### ISSUE THREAD

**Issue by techhubhub** [hbstack/theme-cards#135]
For example, on desktop as:

<img width="1236" alt="image" src="https://github.com/hbstack/theme-cards/assets/158099291/55c8d674-090c-4516-9234-fb544ed925db">

no mobile as:

<img width="377" alt="image" src="https://github.com/hbstack/theme-cards/assets/158099291/6f5d3d25-f287-47bc-ae47-af46da7b3b22">

I tried to hide the search on desktop with header/layouts/partials/hb/modules/header/index.html for hours , but it will also hidden on mobile.  

any tip achieving on hiding the search on desktop, but shown on mobile(breakpoint). Thank you.

**Comment by razonyang** [comment]
It requires to change the styles (CSS), https://hbstack.dev/docs/advanced/style/.

Will provide a sample if I find some time.

**Comment by razonyang** [comment]
Btw, it won't be added into the module, I don't see any reason to hide the search form on desktop... Please describe if you have any use case.

**Comment by techhubhub** [comment]
because with full width or full width: false, the search option up to the right top is too far way although with the short key option (personal opinion).  I would rather not having it, but would like to add it else where once under the theme better. Please provide such sample, thank you in advance.

**Comment by razonyang** [comment]
> because with full width or full width: false, the search option up to the right top is too far way although with the short key option

Sounds like a bug, could you please provide a screenshot about this, to help me understand this issue correctly? Because I didn't see a problem when setting `header.fullWidth` as `false`.

![image](https://github.com/hbstack/theme-cards/assets/17720932/8669144b-f9a3-4ce6-927e-c31973a5a30d)

**Comment by razonyang** [comment]
FWIW,  here you go.

```scss
#hb-header-search-input,
.hb-header-search-keys {
  display: none !important;
}

@include media-breakpoint-up($hb-header-breakpoint) {
  .hb-header-search-icon {
    display: none !important;
  }
}
```
