### ISSUE TITLE
Rewrite homepage to particular page

### ISSUE THREAD

**Issue by stardoom4** [hbstack/theme-cards#234]
Hello , Is there a way to use the docs module as the Index page and blog module as a Blog page , like in Docusaurus.

**Comment by razonyang** [comment]
You can customize the homepage to be a landing page, and write any content you want.

```markdown
// content/_index.md
---
layout: landing
# full_width: true
---

Use Markdown and shortcodes to generate any content.
```

| Example | Source code |
| - | - |
| https://docker.hugomods.com/ | https://github.com/hugomods/site/blob/main/docker/content/_index.md |
| https://images.hugomods.com/ | https://github.com/hugomods/site/blob/main/images/content/_index.md |
| https://echarts.hugomods.com/ | https://github.com/hugomods/site/blob/main/echarts/content/_index.md |
| ... | |

**Comment by stardoom4** [comment]
thanks for the help but what if i dont want to include the landing page and use a docs page as a index.

**Comment by razonyang** [comment]
Not sure if this what you want, specify the `type` as `docs` on homepage.

```markdown
// content/_index.md
---
type: docs
---
```

**Comment by stardoom4** [comment]
I meant like,  assume that i have a doc page named "page1" and i want set that page as the index page.

**Comment by razonyang** [comment]
Hmm, are you meant to _reuse_ the content and layout (left sidebar, right sidebar and so on) as same as the "page1_" on homepage? If so, I don't have good idea.

**Comment by stardoom4** [comment]
Yes that is what I wanted to do .

**Comment by razonyang** [comment]
I see, I have an idea now, but naming is difficult, what should we naming this functionality?

**Comment by stardoom4** [comment]
Anything you want .

**Comment by razonyang** [comment]
Available since `github.com/hugomods/base` [v0.6.0](https://github.com/hugomods/base/releases/tag/v0.6.0), check out the hugomods/base#43 to learn how to use it.

**Comment by stardoom4** [comment]
Yep
