### ISSUE TITLE
removing sidebar

### ISSUE THREAD

**Issue by stardoom4** [hbstack/theme-cards#245]
Is it possible to remove the sidebar or just the taxonomy , featured and recent section.

**Comment by stardoom4** [comment]
thanks.

**Comment by stardoom4** [comment]
by the way  , is it possible to remove the comment section also.

**Comment by razonyang** [comment]
> is it possible to remove the comment section also.

It's modular, you can remove the related comments module, then it will disappear.

https://github.com/hbstack/theme-cards/blob/63e1e0ea2723f1bba687fc9ac4eb3db61d5dfb39/exampleSite/config/_default/module.yaml#L28-L30

You can also disable comments by setting `comments` as `false` on front matter for particular pages.

```markdown
---
comments: false
---
```

The other things are similar, read the docs and configurations will solve most issues.

**Comment by stardoom4** [comment]
Thanks for your help.
