### ISSUE TITLE
Feature request: allow changing post image/thumbnail position to left

### ISSUE THREAD

**Issue by LITUATUI** [hbstack/theme-cards#293]
To have a standard list view like we had on the previous theme [HBS](https://hbs.razonyang.com/v1/en/) would be great.

Something like this:

![HBS](https://github.com/hbstack/theme-cards/assets/49299328/54a3924e-c21e-4a64-98fc-5b276b215e11)

Or like the standard list of the [blowfish theme](https://code-chimp.com/) that also looks pretty good.

**Comment by razonyang** [comment]
I've changed the title, since there is no **standard** list.

**Comment by razonyang** [comment]
Available since [github.com/hbstack/blog/releases/tag/v0.28.0](https://github.com/hbstack/blog/releases/tag/v0.28.0).

To do this by setting [hb.blog.post_thumbnail_position](https://hbstack.dev/modules/blog/overview/#site-parameters) as `start`.

**Comment by LITUATUI** [comment]
It's perfect now, thanks!
