### ISSUE TITLE
Is plugin about comment replaceable

### ISSUE THREAD

**Issue by GraceZhuuu** [hbstack/theme-cards#59]
Thanks for your work.
And i have a question as the title, which that comment plugin need authority of github. And this function could be disabled or replaceable.

**Comment by razonyang** [comment]
Hi, you can disable it by removing the corresponding giscus modules from configuration (module.yaml) and related params (params.yaml).

1. github.com/hbstack/blog/modules/giscus
2. github.com/hbstack/docs/modules/giscus

Alternatives:

1. https://hbstack.dev/modules/blog/comments/
2. https://hbstack.dev/modules/docs/comments/

You can request a new one or create your own.

**Comment by GraceZhuuu** [comment]
Ok, i'll try.  
Thanks again, it's a wonderful job.
